---
# Metricbeat Configuration

- name: Installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure docker module
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Start metricbeat service
    command: service metricbeat start

  - name: Enable service filebeat on boot
    systemd:
      name: metricbeat
      enabled: yes