---
# Web Servers Configuration

- name: Docker and PHP install
  hosts: webservers
  become: true
  tasks:

  - name: docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: install python3-pip
    apt:
      name: python3-pip
      state: present

  - name: install docker
    pip:
      name: docker
      state: present

  - name: install cyberxsecurity/dvwa
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80
      restart_policy: always

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes